#!/usr/bin/env bash
# Create and run a NAMED Cloudflare tunnel with a permanent hostname.
#
# Unlike `cloudflared tunnel --url`, which invents a new random hostname every
# run, a named tunnel keeps the same URL forever. That matters because the
# frontend's API URL is baked in at build time — a changing hostname means
# editing a Vercel variable and redeploying after every restart.
#
#   ./scripts/tunnel.sh setup     one time: create the tunnel + DNS record
#   ./scripts/tunnel.sh run       run it in the foreground
#   ./scripts/tunnel.sh install   run it permanently as a background service
#   ./scripts/tunnel.sh status    show tunnel and DNS state
#   ./scripts/tunnel.sh uninstall stop the background service
#
# Requires `cloudflared tunnel login` first (opens a browser).

set -euo pipefail

TUNNEL_NAME="${TUNNEL_NAME:-garden-city}"
HOSTNAME_="${TUNNEL_HOSTNAME:-gardencity-api.rianfernando.com}"
LOCAL_URL="${LOCAL_URL:-http://localhost:8000}"
CONFIG_DIR="$HOME/.cloudflared"
CONFIG_FILE="$CONFIG_DIR/config.yml"

die() { echo "ERROR: $*" >&2; exit 1; }

require_login() {
  [ -f "$CONFIG_DIR/cert.pem" ] || die \
    "Not logged in to Cloudflare. Run:  cloudflared tunnel login"
}

tunnel_id() {
  cloudflared tunnel list --output json 2>/dev/null \
    | python3 -c "
import json, sys
try:
    rows = json.load(sys.stdin)
except Exception:
    sys.exit(0)
# 'tunnel list' prints null (not []) when no tunnels exist yet.
for r in (rows or []):
    if r.get('name') == '$TUNNEL_NAME':
        print(r['id'])
        break
"
}

cmd_setup() {
  require_login

  local id
  id="$(tunnel_id)"
  if [ -z "$id" ]; then
    echo "Creating tunnel '$TUNNEL_NAME'..."
    cloudflared tunnel create "$TUNNEL_NAME"
    id="$(tunnel_id)"
  else
    echo "Tunnel '$TUNNEL_NAME' already exists ($id)"
  fi
  [ -n "$id" ] || die "Could not determine the tunnel id."

  echo "Writing $CONFIG_FILE"
  mkdir -p "$CONFIG_DIR"
  cat > "$CONFIG_FILE" <<EOF
# Cloudflare named tunnel for the Garden City AI receptionist.
# Generated by scripts/tunnel.sh — safe to edit.
tunnel: $id
credentials-file: $CONFIG_DIR/$id.json

ingress:
  - hostname: $HOSTNAME_
    service: $LOCAL_URL
    originRequest:
      # Voice turns can take a while on local inference; don't cut them off.
      connectTimeout: 30s
      # Server-Sent Events must not be buffered or streaming speech breaks.
      disableChunkedEncoding: false
      noTLSVerify: true
  # Required catch-all.
  - service: http_status:404
EOF

  echo "Routing DNS $HOSTNAME_ -> $TUNNEL_NAME"
  cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME_" 2>&1 \
    | grep -v "already exists" || true

  cat <<EOF

Setup complete.

  Permanent URL:  https://$HOSTNAME_

Next:
  ./scripts/tunnel.sh run        # foreground, Ctrl-C to stop
  ./scripts/tunnel.sh install    # background service, survives reboot
EOF
}

cmd_run() {
  require_login
  [ -f "$CONFIG_FILE" ] || die "No config. Run: ./scripts/tunnel.sh setup"
  echo "Tunnel https://$HOSTNAME_  ->  $LOCAL_URL"
  exec cloudflared tunnel --config "$CONFIG_FILE" run "$TUNNEL_NAME"
}

cmd_install() {
  require_login
  [ -f "$CONFIG_FILE" ] || die "No config. Run: ./scripts/tunnel.sh setup"
  echo "Installing cloudflared as a background service (needs sudo)..."
  sudo cloudflared --config "$CONFIG_FILE" service install
  sleep 2
  echo "Installed. https://$HOSTNAME_ now stays up across reboots."
}

cmd_uninstall() {
  sudo cloudflared service uninstall || true
  echo "Background service removed."
}

cmd_status() {
  echo "=== tunnels ==="
  cloudflared tunnel list 2>&1 | head -10
  echo
  echo "=== config ==="
  [ -f "$CONFIG_FILE" ] && cat "$CONFIG_FILE" || echo "(none — run setup)"
  echo
  echo "=== reachability ==="
  curl -s -o /dev/null -w "https://$HOSTNAME_/api/health/live -> %%{http_code}\n" \
    --max-time 15 "https://$HOSTNAME_/api/health/live" || echo "unreachable"
}

case "${1:-}" in
  setup)     cmd_setup ;;
  run)       cmd_run ;;
  install)   cmd_install ;;
  uninstall) cmd_uninstall ;;
  status)    cmd_status ;;
  *)
    echo "Usage: $0 {setup|run|install|uninstall|status}"
    echo
    echo "  TUNNEL_HOSTNAME  (default: $HOSTNAME_)"
    echo "  TUNNEL_NAME      (default: $TUNNEL_NAME)"
    exit 1 ;;
esac
